-- Seed Netlify Database with the HA_POS demo data (generated from src/lib/seedData.ts)

-- hospitals
INSERT INTO "hospitals" ("id", "code", "nameAr", "nameEn", "cityAr", "cityEn", "phone") VALUES ('hosp-01', 'KFSH', 'مستشفى الملك فيصل التخصصي ومركز الأبحاث', 'King Faisal Specialist Hospital & Research Centre', 'الرياض', 'Riyadh', '0114647272') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "hospitals" ("id", "code", "nameAr", "nameEn", "cityAr", "cityEn", "phone") VALUES ('hosp-02', 'HMG', 'مجموعة الدكتور سليمان الحبيب الطبية', 'Dr. Sulaiman Al-Habib Medical Group', 'الرياض', 'Riyadh', '0114909999') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "hospitals" ("id", "code", "nameAr", "nameEn", "cityAr", "cityEn", "phone") VALUES ('hosp-03', 'SFH', 'مستشفى قوى الأمن بالرياض', 'Security Forces Hospital', 'الرياض', 'Riyadh', '0118024444') ON CONFLICT ("id") DO NOTHING;

-- insurance_companies
INSERT INTO "insurance_companies" ("id", "code", "nameAr", "nameEn", "phone", "defaultCoveragePercent", "requiresPreApproval") VALUES ('ins-01', 'BUPA', 'شركة بوبا العربية للتأمين التعاوني', 'Bupa Arabia Cooperative Insurance', '8002440307', 80, TRUE) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "insurance_companies" ("id", "code", "nameAr", "nameEn", "phone", "defaultCoveragePercent", "requiresPreApproval") VALUES ('ins-02', 'TAWUNIYA', 'شركة التعاونية للتأمين', 'Tawuniya Insurance Company', '920019990', 75, TRUE) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "insurance_companies" ("id", "code", "nameAr", "nameEn", "phone", "defaultCoveragePercent", "requiresPreApproval") VALUES ('ins-03', 'MEDGULF', 'شركة المتوسط والخليج للتأمين (ميدغلف)', 'Medgulf Insurance', '8004414442', 70, FALSE) ON CONFLICT ("id") DO NOTHING;

-- branches
INSERT INTO "branches" ("id", "code", "nameAr", "nameEn", "cityAr", "cityEn", "addressAr", "addressEn", "phone", "taxNumber", "defaultWarehouseId") VALUES ('br-01', 'BR-01', 'فرع الرياض الرئيسي (السليمانية)', 'Riyadh Main Branch (Sulaymaniyah)', 'الرياض', 'Riyadh', 'شارع الملك عبد العزيز، حي السليمانية', 'King Abdulaziz Road, As Sulaymaniyah', '+966 11 456 7890', '300123456700003', 'wh-01') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "branches" ("id", "code", "nameAr", "nameEn", "cityAr", "cityEn", "addressAr", "addressEn", "phone", "taxNumber", "defaultWarehouseId") VALUES ('br-02', 'BR-02', 'فرع الخبر - المنطقة الشرقية', 'Al-Khobar Branch (Eastern Region)', 'الخبر', 'Al-Khobar', 'طريق الأمير فيصل بن فهد، الحزام الذهبي', 'Prince Faisal Bin Fahd Rd, Al Hizam Al Thahabi', '+966 13 889 1234', '300123456700003', 'wh-02') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "branches" ("id", "code", "nameAr", "nameEn", "cityAr", "cityEn", "addressAr", "addressEn", "phone", "taxNumber", "defaultWarehouseId") VALUES ('br-03', 'BR-03', 'فرع جدة - المنطقة الغربية', 'Jeddah Branch (Western Region)', 'جدة', 'Jeddah', 'طريق المدينة المنورة، حي الحمراء', 'Madinah Road, Al Hamra District', '+966 12 667 8901', '300123456700003', 'wh-03') ON CONFLICT ("id") DO NOTHING;

-- warehouses
INSERT INTO "warehouses" ("id", "branchId", "code", "nameAr", "nameEn") VALUES ('wh-01', 'br-01', 'WH-01', 'المستودع الرئيسي - الرياض', 'Central Warehouse - Riyadh') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "warehouses" ("id", "branchId", "code", "nameAr", "nameEn") VALUES ('wh-02', 'br-02', 'WH-02', 'مستودع فرع الخبر', 'Khobar Branch Stock') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "warehouses" ("id", "branchId", "code", "nameAr", "nameEn") VALUES ('wh-03', 'br-03', 'WH-03', 'مستودع فرع جدة', 'Jeddah Branch Stock') ON CONFLICT ("id") DO NOTHING;

-- users
INSERT INTO "users" ("id", "username", "nameAr", "nameEn", "role", "branchIds", "currentBranchId") VALUES ('usr-01', 'admin', 'د. طارق العتيبي', 'Dr. Tariq Al-Otaibi', 'super_admin', '["br-01","br-02","br-03"]', 'br-01') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "users" ("id", "username", "nameAr", "nameEn", "role", "branchIds", "currentBranchId") VALUES ('usr-02', 'reem_mgr', 'أ. ريم الغامدي', 'Reem Al-Ghamdi', 'branch_manager', '["br-01"]', 'br-01') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "users" ("id", "username", "nameAr", "nameEn", "role", "branchIds", "currentBranchId") VALUES ('usr-03', 'faisal_pos', 'فيصل الحربي (كاشير)', 'Faisal Al-Harbi (Cashier)', 'cashier', '["br-01"]', 'br-01') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "users" ("id", "username", "nameAr", "nameEn", "role", "branchIds", "currentBranchId") VALUES ('usr-04', 'dr_huda', 'د. هدى الشهري (سمعيات)', 'Dr. Huda Al-Shehri (Audiologist)', 'audiologist', '["br-01","br-02"]', 'br-01') ON CONFLICT ("id") DO NOTHING;

-- doctors
INSERT INTO "doctors" ("id", "nameAr", "nameEn", "specialtyAr", "specialtyEn", "phone", "hospitalId", "commissionPercent") VALUES ('doc-01', 'د. أحمد المنصور', 'Dr. Ahmed Al-Mansoor', 'استشاري أنف وأذن وحنجرة وجراحة قاع الجمجمة', 'Consultant ENT & Skull Base Surgery', '+966 50 111 2233', 'hosp-02', 10) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "doctors" ("id", "nameAr", "nameEn", "specialtyAr", "specialtyEn", "phone", "hospitalId", "commissionPercent") VALUES ('doc-02', 'د. سارة الحسيني', 'Dr. Sara Al-Husseini', 'استشارية طب السمع والاتزان والتأهيل السمعي', 'Consultant Audiovestibular Medicine', '+966 55 222 3344', 'hosp-01', 12) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "doctors" ("id", "nameAr", "nameEn", "specialtyAr", "specialtyEn", "phone", "hospitalId", "commissionPercent") VALUES ('doc-03', 'د. خالد البيشي', 'Dr. Khalid Al-Bishi', 'أخصائي أول أنف وأذن وحنجرة', 'Senior Specialist ENT', '+966 54 333 4455', 'hosp-03', 8) ON CONFLICT ("id") DO NOTHING;

-- items
INSERT INTO "items" ("id", "sku", "barcode", "nameAr", "nameEn", "category", "brand", "model", "unit", "costPrice", "salePrice", "taxRate", "hasSerials", "warrantyMonths", "minStockLevel", "stockByWarehouse") VALUES ('item-ha-01', 'HA-OT-M1', '628100100101', 'سماعة أوتيكون مور 1 قابلة للشحن (Oticon More 1 miniRITE R)', 'Oticon More 1 miniRITE R Rechargeable Hearing Aid', 'hearing_aids', 'Oticon', 'More 1 miniRITE R', 'قطعة', 9500, 14500, 0.15, TRUE, 24, 3, '{"wh-01":8,"wh-02":3,"wh-03":2}') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "items" ("id", "sku", "barcode", "nameAr", "nameEn", "category", "brand", "model", "unit", "costPrice", "salePrice", "taxRate", "hasSerials", "warrantyMonths", "minStockLevel", "stockByWarehouse") VALUES ('item-ha-02', 'HA-PH-L90', '628100100102', 'سماعة فوناك أوديو لوميتي 90 (Phonak Audeo Lumity L90-R)', 'Phonak Audeo Lumity L90-R Hearing Aid', 'hearing_aids', 'Phonak', 'Lumity L90-R', 'قطعة', 10200, 16000, 0.15, TRUE, 36, 2, '{"wh-01":5,"wh-02":2,"wh-03":1}') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "items" ("id", "sku", "barcode", "nameAr", "nameEn", "category", "brand", "model", "unit", "costPrice", "salePrice", "taxRate", "hasSerials", "warrantyMonths", "minStockLevel", "stockByWarehouse") VALUES ('item-ha-03', 'HA-SG-7AX', '628100100103', 'سماعة سيجنيا بيور تشارج أند جو 7AX (Signia Pure Charge&Go 7AX)', 'Signia Pure Charge&Go 7AX Hearing Aid', 'hearing_aids', 'Signia', 'Pure Charge&Go 7AX', 'قطعة', 8800, 13800, 0.15, TRUE, 24, 3, '{"wh-01":6,"wh-02":4,"wh-03":2}') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "items" ("id", "sku", "barcode", "nameAr", "nameEn", "category", "brand", "model", "unit", "costPrice", "salePrice", "taxRate", "hasSerials", "warrantyMonths", "minStockLevel", "stockByWarehouse") VALUES ('item-ha-04', 'HA-WD-440', '628100100104', 'سماعة وايدكس مومنت شير 440 (Widex Moment Sheer 440)', 'Widex Moment Sheer s-RIC 440 Hearing Aid', 'hearing_aids', 'Widex', 'Moment Sheer 440', 'قطعة', 9800, 15200, 0.15, TRUE, 24, 2, '{"wh-01":4,"wh-02":1,"wh-03":1}') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "items" ("id", "sku", "barcode", "nameAr", "nameEn", "category", "brand", "model", "unit", "costPrice", "salePrice", "taxRate", "hasSerials", "warrantyMonths", "minStockLevel", "stockByWarehouse") VALUES ('item-em-01', 'EM-ACRYLIC', '628200200101', 'قالب أذن أكريليك صلب مخصص (Hard Acrylic Earmold)', 'Custom Hard Acrylic Earmold with Vent', 'earmolds', 'Custom Lab', 'Hard Acrylic', 'قالب', 180, 450, 0.15, FALSE, 6, 10, '{"wh-01":999,"wh-02":999,"wh-03":999}') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "items" ("id", "sku", "barcode", "nameAr", "nameEn", "category", "brand", "model", "unit", "costPrice", "salePrice", "taxRate", "hasSerials", "warrantyMonths", "minStockLevel", "stockByWarehouse") VALUES ('item-em-02', 'EM-SILICONE', '628200200102', 'قالب أذن سيليكون ناعم مخصص (Soft Silicone Earmold)', 'Custom Soft Silicone Earmold', 'earmolds', 'Custom Lab', 'Soft Silicone', 'قالب', 220, 550, 0.15, FALSE, 6, 10, '{"wh-01":999,"wh-02":999,"wh-03":999}') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "items" ("id", "sku", "barcode", "nameAr", "nameEn", "category", "brand", "model", "unit", "costPrice", "salePrice", "taxRate", "hasSerials", "warrantyMonths", "minStockLevel", "stockByWarehouse") VALUES ('item-em-03', 'EM-MICROCIC', '628200200103', 'هيكل مخصص داخل القناة ميكرو (Custom Micro-CIC Shell)', 'Custom Micro-CIC Modular Shell', 'earmolds', 'Custom Lab', 'Micro-CIC Shell', 'قطعة', 350, 850, 0.15, FALSE, 12, 5, '{"wh-01":999,"wh-02":999,"wh-03":999}') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "items" ("id", "sku", "barcode", "nameAr", "nameEn", "category", "brand", "model", "unit", "costPrice", "salePrice", "taxRate", "hasSerials", "warrantyMonths", "minStockLevel", "stockByWarehouse") VALUES ('item-bat-312', 'BAT-312-RAY', '628300300312', 'بطاريات ريوفاك حجم 312 بنية (كرتون 6 حبات)', 'Rayovac Extra Advanced Size 312 Hearing Aid Batteries (Pack of 6)', 'batteries', 'Rayovac', 'Size 312 Brown', 'كرتون', 18, 45, 0.15, FALSE, 0, 25, '{"wh-01":140,"wh-02":85,"wh-03":60}') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "items" ("id", "sku", "barcode", "nameAr", "nameEn", "category", "brand", "model", "unit", "costPrice", "salePrice", "taxRate", "hasSerials", "warrantyMonths", "minStockLevel", "stockByWarehouse") VALUES ('item-bat-10', 'BAT-10-RAY', '628300300010', 'بطاريات ريوفاك حجم 10 صفراء (كرتون 6 حبات)', 'Rayovac Extra Advanced Size 10 Batteries (Pack of 6)', 'batteries', 'Rayovac', 'Size 10 Yellow', 'كرتون', 18, 45, 0.15, FALSE, 0, 20, '{"wh-01":90,"wh-02":45,"wh-03":30}') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "items" ("id", "sku", "barcode", "nameAr", "nameEn", "category", "brand", "model", "unit", "costPrice", "salePrice", "taxRate", "hasSerials", "warrantyMonths", "minStockLevel", "stockByWarehouse") VALUES ('item-bat-13', 'BAT-13-RAY', '628300300013', 'بطاريات ريوفاك حجم 13 برتقالية (كرتون 6 حبات)', 'Rayovac Extra Advanced Size 13 Batteries (Pack of 6)', 'batteries', 'Rayovac', 'Size 13 Orange', 'كرتون', 18, 45, 0.15, FALSE, 0, 15, '{"wh-01":70,"wh-02":35,"wh-03":25}') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "items" ("id", "sku", "barcode", "nameAr", "nameEn", "category", "brand", "model", "unit", "costPrice", "salePrice", "taxRate", "hasSerials", "warrantyMonths", "minStockLevel", "stockByWarehouse") VALUES ('item-bat-675', 'BAT-675-RAY', '628300300675', 'بطاريات ريوفاك حجم 675 زرقاء عالية الطاقة (للقوقعة والسماعات القوية)', 'Rayovac Extra Advanced Size 675 Blue High Power (Pack of 6)', 'batteries', 'Rayovac', 'Size 675 Blue', 'كرتون', 22, 55, 0.15, FALSE, 0, 10, '{"wh-01":45,"wh-02":18,"wh-03":12}') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "items" ("id", "sku", "barcode", "nameAr", "nameEn", "category", "brand", "model", "unit", "costPrice", "salePrice", "taxRate", "hasSerials", "warrantyMonths", "minStockLevel", "stockByWarehouse") VALUES ('item-sp-cs', 'SP-PH-CS', '628400400101', 'قرص فلاتر شمعية فوناك سيروشيلد (CeruShield Disk)', 'Phonak CeruShield Wax Filter Disk', 'spare_parts', 'Phonak', 'CeruShield Disk', 'قرص', 35, 75, 0.15, FALSE, 0, 15, '{"wh-01":60,"wh-02":30,"wh-03":20}') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "items" ("id", "sku", "barcode", "nameAr", "nameEn", "category", "brand", "model", "unit", "costPrice", "salePrice", "taxRate", "hasSerials", "warrantyMonths", "minStockLevel", "stockByWarehouse") VALUES ('item-sp-pw', 'SP-OT-PW', '628400400102', 'فلاتر شمعية أوتيكون بروفاكس ميني فيت (ProWax miniFit)', 'Oticon ProWax miniFit Filters', 'spare_parts', 'Oticon', 'ProWax miniFit', 'باكيت', 32, 70, 0.15, FALSE, 0, 15, '{"wh-01":50,"wh-02":25,"wh-03":15}') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "items" ("id", "sku", "barcode", "nameAr", "nameEn", "category", "brand", "model", "unit", "costPrice", "salePrice", "taxRate", "hasSerials", "warrantyMonths", "minStockLevel", "stockByWarehouse") VALUES ('item-acc-tv', 'ACC-PH-TV', '628500500101', 'جهاز بث التلفزيون اللاسلكي فوناك (Phonak TV Connector)', 'Phonak TV Connector Wireless Audio Streamer', 'accessories', 'Phonak', 'TV Connector V2', 'جهاز', 550, 950, 0.15, TRUE, 12, 3, '{"wh-01":8,"wh-02":3,"wh-03":2}') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "items" ("id", "sku", "barcode", "nameAr", "nameEn", "category", "brand", "model", "unit", "costPrice", "salePrice", "taxRate", "hasSerials", "warrantyMonths", "minStockLevel", "stockByWarehouse") VALUES ('item-acc-dry', 'ACC-UV-DRY', '628500500102', 'جهاز تجفيف وتعقيم السماعات بالأشعة فوق البنفسجية (Dry-Cap UV)', 'Flow-Med Dry-Cap UV 2 Electronic Hearing Aid Dryer', 'accessories', 'Flow-Med', 'Dry-Cap UV 2', 'جهاز', 210, 380, 0.15, FALSE, 12, 4, '{"wh-01":14,"wh-02":6,"wh-03":5}') ON CONFLICT ("id") DO NOTHING;

-- serial_units
INSERT INTO "serial_units" ("id", "itemId", "serialNumber", "branchId", "warehouseId", "status") VALUES ('sn-01', 'item-ha-01', 'OT-M1-889104', 'br-01', 'wh-01', 'in_stock') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "serial_units" ("id", "itemId", "serialNumber", "branchId", "warehouseId", "status") VALUES ('sn-02', 'item-ha-01', 'OT-M1-889105', 'br-01', 'wh-01', 'in_stock') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "serial_units" ("id", "itemId", "serialNumber", "branchId", "warehouseId", "status") VALUES ('sn-03', 'item-ha-02', 'PH-L9-440219', 'br-01', 'wh-01', 'in_stock') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "serial_units" ("id", "itemId", "serialNumber", "branchId", "warehouseId", "status") VALUES ('sn-04', 'item-ha-02', 'PH-L9-440220', 'br-02', 'wh-02', 'in_stock') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "serial_units" ("id", "itemId", "serialNumber", "branchId", "warehouseId", "status", "clientId", "invoiceId", "warrantyEndDate") VALUES ('sn-05', 'item-ha-03', 'SG-7A-331088', 'br-01', 'wh-01', 'sold', 'cl-01', 'inv-1001', '2028-09-15') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "serial_units" ("id", "itemId", "serialNumber", "branchId", "warehouseId", "status", "clientId") VALUES ('sn-06', 'item-ha-04', 'WD-44-129033', 'br-01', 'wh-01', 'trial', 'cl-02') ON CONFLICT ("id") DO NOTHING;

-- clients
INSERT INTO "clients" ("id", "fileNo", "nationalId", "nameAr", "nameEn", "phone", "secondaryPhone", "gender", "dob", "age", "cityAr", "cityEn", "address", "doctorId", "hospitalId", "insuranceId", "insurancePolicyNo", "notes", "createdAt") VALUES ('cl-01', 'F-2026-0104', '1048294821', 'محمد بن سلطان القحطاني', 'Muhammad Sultan Al-Qahtani', '0505123456', '0555678901', 'male', '1968-04-12', 58, 'الرياض', 'Riyadh', 'حي النخيل، شارع الأمير نايف، فيلا 24', 'doc-01', 'hosp-02', 'ins-01', 'BUP-884920-KSA', 'ضعف سمع حسي عصبي ثنائي تدريجي، يستخدم سماعة سيجنيا منذ شهر', '2026-02-10') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "clients" ("id", "fileNo", "nationalId", "nameAr", "nameEn", "phone", "gender", "dob", "age", "cityAr", "cityEn", "address", "doctorId", "hospitalId", "insuranceId", "insurancePolicyNo", "notes", "createdAt") VALUES ('cl-02', 'F-2026-0105', '2019482710', 'نورة بنت صالح الدوسري', 'Noura Saleh Al-Dosari', '0544987654', 'female', '1984-11-20', 42, 'الرياض', 'Riyadh', 'حي الملقا، طريق أنس بن مالك', 'doc-02', 'hosp-01', 'ins-02', 'TAW-492019', 'تعاني من طنين في الأذن اليسرى مع فقدان سمع متوسط، قيد التجربة لسماعة وايدكس', '2026-03-01') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "clients" ("id", "fileNo", "nationalId", "nameAr", "nameEn", "phone", "gender", "dob", "age", "cityAr", "cityEn", "address", "doctorId", "hospitalId", "notes", "createdAt") VALUES ('cl-03', 'F-2026-0106', '1099238472', 'عبدالله بن فهد الغامدي', 'Abdullah Fahad Al-Ghamdi', '0567123987', 'male', '1959-08-05', 67, 'الخبر', 'Al-Khobar', 'حي الراكة الجنوبية، شارع مكة', 'doc-03', 'hosp-03', 'تم طلب قالب سيليكون ناعم للأذنين، مراجع منتظم لفحص السمع السنوي', '2026-04-15') ON CONFLICT ("id") DO NOTHING;

-- audiograms
INSERT INTO "audiograms" ("id", "clientId", "date", "audiologistName", "testType", "frequencies", "leftAir", "rightAir", "leftBone", "rightBone", "ptaLeft", "ptaRight", "sdsLeft", "sdsRight", "notes") VALUES ('aud-01', 'cl-01', '2026-03-05', 'د. هدى الشهري', 'فحص النغمات النقية الشامل (Pure Tone Audiometry)', '[125,250,500,1000,2000,4000,8000]', '{"125":25,"250":30,"500":45,"1000":55,"2000":65,"4000":75,"8000":80}', '{"125":20,"250":25,"500":40,"1000":50,"2000":60,"4000":70,"8000":75}', '{"250":25,"500":40,"1000":50,"2000":60,"4000":70}', '{"250":20,"500":35,"1000":45,"2000":55,"4000":65}', 55, 50, 84, 88, 'ضعف سمع حسي عصبي متناظر منحدر للترددات العالية (Sloping Sensorineural Hearing Loss). استجابة ممتازة مع المعينات الرقمية المتطورة.') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "audiograms" ("id", "clientId", "date", "audiologistName", "testType", "frequencies", "leftAir", "rightAir", "leftBone", "rightBone", "ptaLeft", "ptaRight", "sdsLeft", "sdsRight", "notes") VALUES ('aud-02', 'cl-02', '2026-03-12', 'د. هدى الشهري', 'فحص سمعي تشخيصي مع اختبار تمييز الكلام', '[125,250,500,1000,2000,4000,8000]', '{"125":20,"250":25,"500":35,"1000":45,"2000":50,"4000":60,"8000":65}', '{"125":15,"250":20,"500":20,"1000":25,"2000":30,"4000":35,"8000":40}', '{"250":20,"500":30,"1000":40,"2000":45,"4000":55}', '{"250":15,"500":15,"1000":20,"2000":25,"4000":30}', 43.3, 25, 80, 96, 'فقدان سمع حسي عصبي متوسط بالأذن اليسرى وطبيعي إلى بسيط بالأذن اليمنى. يوصى ببرمجة تقنية تقليل الطنين.') ON CONFLICT ("id") DO NOTHING;

-- earmold_orders
INSERT INTO "earmold_orders" ("id", "orderNo", "clientId", "ear", "shellType", "color", "ventType", "deviceBrand", "deviceModel", "impressionDate", "impressionBy", "workshop", "expectedDate", "status", "price", "cost", "notes", "createdAt") VALUES ('emo-01', 'EMO-2026-0042', 'cl-03', 'both', 'soft_silicone', 'beige', '1.5mm', 'Phonak', 'Naida Paradise P70-UP', '2026-09-10', 'أخصائي المعمل / سامي', 'معمل الأمل للقوالب والتعويضات السمعية', '2026-09-18', 'ready', 1100, 440, 'المريض يعاني من ارتجاع صفير بالهيكل القديم، يرجى ضبط القناة بإحكام مريح وتنفيس متوازي 1.5 مم.', '2026-09-10T11:00:00Z') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "earmold_orders" ("id", "orderNo", "clientId", "ear", "shellType", "color", "ventType", "deviceBrand", "deviceModel", "impressionDate", "impressionBy", "workshop", "expectedDate", "status", "price", "cost", "notes", "createdAt") VALUES ('emo-02', 'EMO-2026-0043', 'cl-01', 'left', 'hard_acrylic', 'clear', '2.0mm', 'Oticon', 'More 1 miniRITE R (Micro-mold)', '2026-09-14', 'د. هدى الشهري', 'الورشة الفنية الداخلية - فرع الرياض', '2026-09-20', 'in_production', 450, 180, 'قالب مايكرو مدمج مع سماعة ريسيفر 85 ديسيبل.', '2026-09-14T09:30:00Z') ON CONFLICT ("id") DO NOTHING;

-- invoices
INSERT INTO "invoices" ("id", "invoiceNo", "date", "deliveryDate", "branchId", "warehouseId", "costCenter", "workshop", "clientId", "doctorId", "hospitalId", "sellerName", "lines", "subtotalBeforeTax", "totalDiscount", "taxAmount", "grandTotal", "depositPaid", "amountPaid", "remainingDue", "paymentMethod", "paymentDetails", "isInsurance", "deliveryStatus", "status", "notes") VALUES ('inv-1001', 'INV-2026-0089', '2026-09-15', '2026-09-15 16:30', 'br-01', 'wh-01', 'CC-RIYADH-01', 'الورشة الفنية الداخلية - فرع الرياض', 'cl-01', 'doc-01', 'hosp-02', 'فيصل الحربي', '[{"id":"ln-01","itemId":"item-ha-03","itemCode":"HA-SG-7AX","itemNameAr":"سماعة سيجنيا بيور تشارج أند جو 7AX","itemNameEn":"Signia Pure Charge&Go 7AX Hearing Aid","unit":"قطعة","quantity":1,"unitPrice":13800,"grossAmount":13800,"discountPercent":10,"discountValue":1380,"netAmount":12420,"taxPercent":15,"taxAmount":1863,"totalAmount":14283,"warehouseId":"wh-01","serialNumbers":["SG-7A-331088"],"isDelivered":true,"isReady":true,"isTrial":false,"notes":"برمجة جلسة أولى + ضمان 24 شهر شامل الصيانة"},{"id":"ln-02","itemId":"item-bat-312","itemCode":"BAT-312-RAY","itemNameAr":"بطاريات ريوفاك حجم 312 بنية (كرتون 6 حبات)","itemNameEn":"Rayovac Extra Advanced Size 312 (Pack of 6)","unit":"كرتون","quantity":2,"unitPrice":45,"grossAmount":90,"discountPercent":0,"discountValue":0,"netAmount":90,"taxPercent":15,"taxAmount":13.5,"totalAmount":103.5,"warehouseId":"wh-01","isDelivered":true,"isReady":true,"isTrial":false}]', 12510, 1380, 1876.5, 14386.5, 2000, 12386.5, 0, 'split', '{"cashAmount":2386.5,"madaAmount":10000,"visaAmount":0,"insuranceAmount":0,"depositAmount":2000}', FALSE, 'delivered', 'active', 'تم تسليم الجهاز كامل مع علبة الشحن والشاحن والبطاريات الإضافية.') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "invoices" ("id", "invoiceNo", "date", "deliveryDate", "branchId", "warehouseId", "costCenter", "workshop", "clientId", "doctorId", "hospitalId", "sellerName", "lines", "subtotalBeforeTax", "totalDiscount", "taxAmount", "grandTotal", "depositPaid", "amountPaid", "remainingDue", "paymentMethod", "paymentDetails", "isInsurance", "deliveryStatus", "status", "notes") VALUES ('inv-1002', 'INV-2026-0090', '2026-09-16', '2026-09-18 18:00', 'br-01', 'wh-01', 'CC-RIYADH-01', 'الورشة الفنية الداخلية - فرع الرياض', 'cl-02', 'doc-02', 'hosp-01', 'فيصل الحربي', '[{"id":"ln-03","itemId":"item-ha-04","itemCode":"HA-WD-440","itemNameAr":"سماعة وايدكس مومنت شير 440 (تجربة مريض)","itemNameEn":"Widex Moment Sheer 440 (Trial)","unit":"قطعة","quantity":1,"unitPrice":15200,"grossAmount":15200,"discountPercent":15,"discountValue":2280,"netAmount":12920,"taxPercent":15,"taxAmount":1938,"totalAmount":14858,"warehouseId":"wh-01","serialNumbers":["WD-44-129033"],"isDelivered":false,"isReady":true,"isTrial":true,"notes":"صرف بموجب خطاب تجربة لمدة أسبوعين مع تأمين مسترد"}]', 12920, 2280, 1938, 14858, 3000, 3000, 11858, 'mada', '{"cashAmount":0,"madaAmount":3000,"visaAmount":0,"insuranceAmount":0,"depositAmount":3000}', FALSE, 'trial', 'active', 'خطاب تجربة رسمي معتمد من أخصائية السمعيات.') ON CONFLICT ("id") DO NOTHING;

-- stock_transfers
INSERT INTO "stock_transfers" ("id", "transferNo", "fromBranchId", "fromWarehouseId", "toBranchId", "toWarehouseId", "status", "requestedBy", "approvedBy", "receivedBy", "items", "createdAt", "completedAt", "notes") VALUES ('tr-01', 'TR-2026-0012', 'br-01', 'wh-01', 'br-02', 'wh-02', 'completed', 'أ. ريم الغامدي', 'د. طارق العتيبي', 'أمين مستودع الخبر', '[{"itemId":"item-ha-02","itemCode":"HA-PH-L90","itemNameAr":"سماعة فوناك أوديو لوميتي 90","itemNameEn":"Phonak Audeo Lumity L90-R","quantity":1,"serials":["PH-L9-440220"]},{"itemId":"item-bat-312","itemCode":"BAT-312-RAY","itemNameAr":"بطاريات ريوفاك حجم 312 بنية","itemNameEn":"Rayovac Extra Advanced Size 312","quantity":20}]', '2026-09-08T10:00:00Z', '2026-09-10T14:30:00Z', 'تعزيز مخزون فرع الخبر لتلبية طلبات العيادة.') ON CONFLICT ("id") DO NOTHING;

-- message_templates
INSERT INTO "message_templates" ("id", "trigger", "titleAr", "titleEn", "bodyAr", "bodyEn") VALUES ('tmpl-01', 'order_ready', 'إشعار جاهزية القالب أو السماعة', 'Order Ready Notification', 'مرحباً عزيزنا العميل {client_name}، نود إبلاغكم بأن طلبكم رقم ({order_no}) الخاص بالقالب/السماعة الطبية أصبح جاهزاً للاستلام والتجربة في {branch}. نتشرف بزيارتكم.', 'Dear {client_name}, your custom earmold/hearing aid order ({order_no}) is now ready for pickup and fitting at {branch}. We look forward to your visit.') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "message_templates" ("id", "trigger", "titleAr", "titleEn", "bodyAr", "bodyEn") VALUES ('tmpl-02', 'invoice_receipt', 'نسخة الفاتورة الإلكترونية', 'Invoice & Receipt Copy', 'شكراً لثقتكم بنا، عزيزنا {client_name}. تم إصدار فاتورتكم رقم ({invoice_no}) بمبلغ إجمالي {grand_total} ر.س والمتبقي {remaining_due} ر.س. نتمنى لكم دوام الصحة والعافية.', 'Thank you for choosing us, {client_name}. Your invoice ({invoice_no}) has been generated for {grand_total} SAR. Remaining balance: {remaining_due} SAR.') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "message_templates" ("id", "trigger", "titleAr", "titleEn", "bodyAr", "bodyEn") VALUES ('tmpl-03', 'appointment', 'تذكير بموعد الفحص أو البرمجة', 'Fitting Appointment Reminder', 'نذكركم بموعدكم القادم لجلسة فحص السمع وبرمجة السماعة يوم {date} في {branch} مع الأخصائي المعالج. يرجى تأكيد الحضور.', 'Reminder of your upcoming audiology / fitting appointment on {date} at {branch}. Please confirm your attendance.') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "message_templates" ("id", "trigger", "titleAr", "titleEn", "bodyAr", "bodyEn") VALUES ('tmpl-04', 'battery_reminder', 'تذكير بطاريات وصيانة وقائية', 'Battery & Maintenance Reminder', 'عزيزنا {client_name}، حفاظاً على كفاءة سماعتكم الطبية، يسعدنا تذكيركم بمرور 6 أشهر على استلام السماعة لعمل فحص دوري مجاني واستلام حزمة بطاريات وفلاتر جديدة من أقرب فرع.', 'Dear {client_name}, to keep your hearing aid performing at its best, you are invited for a complimentary periodic checkup and maintenance at {branch}.') ON CONFLICT ("id") DO NOTHING;

-- message_logs
INSERT INTO "message_logs" ("id", "clientId", "clientName", "phone", "channel", "trigger", "content", "status", "sentAt") VALUES ('msg-01', 'cl-01', 'محمد بن سلطان القحطاني', '0505123456', 'whatsapp', 'invoice_receipt', 'شكراً لثقتكم بنا، عزيزنا محمد بن سلطان القحطاني. تم إصدار فاتورتكم رقم (INV-2026-0089) بمبلغ إجمالي 14386.5 ر.س والمتبقي 0 ر.س.', 'delivered', '2026-09-15 16:35') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "message_logs" ("id", "clientId", "clientName", "phone", "channel", "trigger", "content", "status", "sentAt") VALUES ('msg-02', 'cl-03', 'عبدالله بن فهد الغامدي', '0567123987', 'whatsapp', 'order_ready', 'مرحباً عزيزنا العميل عبدالله بن فهد الغامدي، نود إبلاغكم بأن طلبكم رقم (EMO-2026-0042) الخاص بالقالب أصبح جاهزاً للاستلام.', 'sent', '2026-09-16 11:20') ON CONFLICT ("id") DO NOTHING;

-- audit_logs
INSERT INTO "audit_logs" ("id", "timestamp", "userId", "userName", "branchId", "action", "entityType", "entityId", "details") VALUES ('aud-log-01', '2026-09-15 16:30', 'usr-03', 'فيصل الحربي', 'br-01', 'CREATE_INVOICE', 'INVOICE', 'inv-1001', 'تم إصدار الفاتورة رقم INV-2026-0089 للعميل محمد بن سلطان القحطاني بقيمة 14,386.5 ر.س مع خصم 1,380 ر.س') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "audit_logs" ("id", "timestamp", "userId", "userName", "branchId", "action", "entityType", "entityId", "details") VALUES ('aud-log-02', '2026-09-10 14:30', 'usr-01', 'د. طارق العتيبي', 'br-01', 'APPROVE_TRANSFER', 'STOCK_TRANSFER', 'tr-01', 'اعتماد تحويل مخزني رقم TR-2026-0012 من مستودع الرياض إلى مستودع الخبر') ON CONFLICT ("id") DO NOTHING;
